### ISSUE TITLE
commentstring can be blank

### ISSUE THREAD

**Issue by AaronLasseigne** [AaronLasseigne/yank-code#3]
Vim allows for blank comment strings for types like JSON. In this case, do not show a header.

**Comment by AaronLasseigne** [comment]
If you really want a comment in a type that doesn't normally have a comment type you can always override the existing `commentstring`.

```vim
autocmd FileType json setlocal commentstring=//\ %s
```

This may have weird effects elsewhere though as `commentstring` is a vim variable that can be used in a variety of plugins.

**Comment by danbruegge** [comment]
Alright good to know. Thank you. :)
